### ISSUE TITLE
Model folder missing

### ISSUE THREAD

**Issue by inra0** [BBC-Esq/VectorDB-Plugin-for-LM-Studio#166]
![image](https://github.com/BBC-Esq/VectorDB-Plugin-for-LM-Studio/assets/32350438/a0929cfe-036f-40b8-bd3d-6a2461fe2194)
![image](https://github.com/BBC-Esq/VectorDB-Plugin-for-LM-Studio/assets/32350438/71684a23-729a-44d6-8b58-18334a9ebe44)
![image](https://github.com/BBC-Esq/VectorDB-Plugin-for-LM-Studio/assets/32350438/4f4d8ef1-6f6e-417a-8c86-2695ae6c01b3)

When I query with chunks only, it works but when I unchecked the chunk only, it pop up warning as the first image. Solar Instruct folder is missing, but the options in models says that its already downloaded.

After the error warning, I cant click "submit question" button

**Comment by BBC-Esq** [comment]
I don't see the solar model within the folder containing the other models, which is the last image.  That is very strange.  Also, I'm not sure why there is the 12b model from stabilityai showing; that was removed from my release (but still left commented out I believe).  Can you try closing down the program, restarting, and sending me a screenshot of what the models tab looks like.  It should not be showing solar as downloaded unless there's a specific folder for it in the "Models" folder...

It should say "no" and allow you to download it.  

Also, can you try some of the other chat models to see if they're working?

Lastly, I noticed that you're getting a pynvml error...what graphics card are you using?

**Comment by inra0** [comment]
![image](https://github.com/BBC-Esq/VectorDB-Plugin-for-LM-Studio/assets/32350438/ac902f62-2def-4e56-916a-b00f1775c892)
![image](https://github.com/BBC-Esq/VectorDB-Plugin-for-LM-Studio/assets/32350438/5ce4e207-89b0-42f9-9982-e7735467e01b)
![image](https://github.com/BBC-Esq/VectorDB-Plugin-for-LM-Studio/assets/32350438/5aeef976-9846-4ac2-b285-0ceb9cc0a26d)
![image](https://github.com/BBC-Esq/VectorDB-Plugin-for-LM-Studio/assets/32350438/74d24a9d-9358-42d2-95e6-6d2df8d49398)

I'm using laptop with dual graphic, AMD and RTX 3050 (recent update, latest cuda installed)
restarted, download dolphin llama3. Works on chunks only, but seems I run out of gpu ram when chunk only unchecked

**Comment by BBC-Esq** [comment]
Yep, unchecking "chunks only" wouldn't change the vram usage, the model would still be loaded.  But it's SUPPOSED to automatically remove the "local" model when you choose the use LM Studio radio button...With that being said, check out the release page and it shows that dolphin uses 9.2 gb.  Also, my program doesn't yet have the ability to use multiple gpus.

I'm seriously considering switching to llama-cpp, which allows one to offload part to the GPU and part to system ram...but I wanted to get this release out ASAP.  Let me know if reloading and restarting allows you to download the solar model please.

**Comment by inra0** [comment]
No, I can't download solar model after restart
Gpu 0 (rtx) is use by default.

**Comment by BBC-Esq** [comment]
Does your VRAM usage roughly match what my release page says it should be for the various models?  Are you still unable to download the SOLAR model?  Any more details?

**Comment by BBC-Esq** [comment]
Feel free to reopen if this issue persists.
