### ISSUE TITLE
.Scriptsctivate: command not found

### ISSUE THREAD

**Issue by DjagbleyEmmanuel** [BBC-Esq/VectorDB-Plugin-for-LM-Studio#176]
.\Scripts\activate
.Scriptsctivate: command not found

**Comment by BBC-Esq** [comment]
Can you give me some basic information like what you were doing with the program when you were doing this, or better yet the full traceback?

**Comment by BBC-Esq** [comment]
I'll close out as unconfirmed in a week unless I hear back from ya.  Thanks.

**Comment by DjagbleyEmmanuel** [comment]
Sorry it took this long, but i had it all sorted out now. Thanks
