### ISSUE TITLE
WinError 3 - Path not found 'Models\\Vector'

### ISSUE THREAD

**Issue by deronkel82** [BBC-Esq/VectorDB-Plugin-for-LM-Studio#227]
Thank you for creating this awesome project! I´m eager to test it but i can´t get it to start:

I´ve followed the installation instructions and run into this error when running the gui.py. The error message is from my second try with conda but it´s exaclty the same i´ve got with the original intructions. The installation routine itself finished without any errors. Any ideas?

PS D:\KI\VectorDB\src> conda activate vecdb
(vecdb) PS D:\KI\VectorDB\src> python .\gui.py
ERROR:root:Error initializing GUI: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'Models\\Vector'
CRITICAL:root:Critical error in main function: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'Models\\Vector'
A critical error occurred. Please check the log file 'gui_log.txt' for details.
QThread: Destroyed while thread is still running
(vecdb) PS D:\KI\VectorDB\src>

**Comment by BBC-Esq** [comment]
Please try release 6.3.0, which I just uploaded.  It should hopefully address this issue.  Thanks for bringing it to my attention.  Let me know if it still doesn't work...

**Comment by BBC-Esq** [comment]
This is the specific release.  I deleted the old 6.3.0 release because of a mistake but this one should hopefully work now:

https://github.com/BBC-Esq/VectorDB-Plugin-for-LM-Studio/releases/tag/v6.3.0
