### ISSUE TITLE
Models tab download progress bar or status

### ISSUE THREAD

**Issue by Prhmma** [BBC-Esq/VectorDB-Plugin-for-LM-Studio#292]
I noticed downloading the model could be a bit confusing because when you click on "Download Selected Model", you don't get a message regarding the download is started or not, and given the size of the models, it will take some time so I thought having a status/progress bar for models download could be a good feature

**Comment by BBC-Esq** [comment]
Added a print statement indicating which model and how much data will be downloaded.  Unfortunately, I'm couldn't figure out a better way when using the "snapshot download" from huggingface.
